{
 "title": "E-Commerce Big Data Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Transacoes Geradas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ecommerce_transacoes_geradas_total"
    }
   ]
  },
  {
   "title": "Buscas Distribuidas Realizadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ecommerce_buscas_realizadas_total"
    }
   ]
  },
  {
   "title": "Taxa de Geracao de Transacoes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ecommerce_transacoes_geradas_total[1m])"
    }
   ]
  },
  {
   "title": "Transacoes Processadas pelo Spark",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ecommerce_transacoes_processadas_total"
    }
   ]
  },
  {
   "title": "Recomendacoes Geradas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    { "expr": "ecommerce_recomendacoes_total" }
   ]
  },
  {
   "title": "Erros no Pipeline Spark",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    { "expr": "ecommerce_spark_erros_total" }
   ]
  }
 ]
}